server:
  port: 8081
spring:
  application:
    name: courses-back
  data:
    mongodb:
      uri: ${MONGODB_URI}/${DB_NAME}
frontend:
  url: ${FRONT_URL}
azure:
  storage:
    connection-string: ${AZURE_BLOB_CONNECTION_STRING}
    container-name: ${CONTAINER_NAME}
