server:
  port: 8081
spring:
  application:
    name: courses-back
  data:
    mongodb:
      uri: ${MONGODB_URI}/${DB_NAME}
frontend:
  url: ${FRONT_URL}
cloudinary:
  cloud_name:
  api_key:
  api_secret:
